import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthProvider from "./_components/AuthProvider/AuthProvider";
import Header from "./_components/Header/Header";

import Toast from "./_components/UI/Toast";
import { ReactNodeType } from "./_types/Index";
import "./globals.css";
import SwrProvider from "./providers/SwrProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNodeType }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <SwrProvider>
            <Header />
            <main className="container">{children}</main>
          </SwrProvider>
        </AuthProvider>
        <Toast />
        <div id="portal"></div>
      </body>
    </html>
  );
}
